### ISSUE TITLE
0.36 crash in Linux

### ISSUE THREAD

**Issue by n8ure-7** [ac2cz/Falcon#73] opened 2020-10-12 16:51 UTC
I'm trying to run version 0.36 in Linux. When my TH-D72 is connected and I open the PacSat software, the software locks up. Sometimes it even locks up the whole computer, which then needs a hard boot. I tried to run it with java on verbose to look for an error code. Here's what I get before it locks up:

[Loaded java.util.SortedSet from /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar]
[Loaded java.util.NavigableSet from /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar]
[Loaded java.util.TreeMap$KeySet from /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar]
[Loaded java.util.TreeMap$PrivateEntryIterator from /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar]
[Loaded java.util.TreeMap$KeyIterator from /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar]
[Loaded sun.management.GarbageCollectionNotifInfoCompositeData$1 from /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar]
[Loaded sun.awt.X11.XErrorEvent from /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar]

The software runs fine when the radio is not connected, or when no com port is set.

**Comment by n8ure-7** [comment] 2020-10-14 11:46
Thanks Chris,

 

I eventually got it working. It may have been a permissions problem. I was originally giving the port permissions with chmod, setting the baud rate with stty, and sending commands to the radio via the echo command. Then I would go to PacSat and it would crash. I later put myself in the dialout group so that I don't have to give permissions with chmod. It now works fine. Another person ran PacSat with sudo and it worked that way too.

 

Thanks for making this very nice software.

 

-Stephen

N8URE

 
 

Sent: Tuesday, October 13, 2020 at 9:24 AM

**Comment by ac2cz** [comment] 2021-02-28 16:35
This looks like a duplicate of #37.  I will fix when I can.  I will close this and keep the early issue open.

**Closed by ac2cz** 2021-02-28 16:35 UTC
Labels: bug, duplicate
